import type { NextApiRequest, NextApiResponse } from 'next'
import { buildAuthoringPrompt, getSchemaFilePath } from '../../../utils/dev/AuthoringPrompt'
import { runCodex } from '../../../utils/dev/CodexClient'
import { generateThumbnail } from '../../../utils/dev/ImageGenerator'
import { collectSeriesThumbnails } from '../../../utils/dev/SeriesResolver'
import { CATEGORIES } from '../../../config/posts.config'
import { GeneratedPost } from '../../../utils/dev/types'

// Belt-and-suspenders: also blocked at pageExtensions layer in production
if (process.env.NODE_ENV === 'production') {
  console.warn('generate-post.dev.ts loaded in production — this should not happen')
}

type SuccessResponse = {
  post: GeneratedPost
  /** Set when $imagegen failed; the client should surface this and offer manual upload fallback. */
  thumbnailGenerationError?: string
  /** True when the thumbnail was auto-generated and downgraded to mode 'reuse'. */
  thumbnailAutoGenerated?: boolean
}
type ErrorResponse = { error: string; detail?: string }

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse<SuccessResponse | ErrorResponse>
) {
  // Production guard
  if (process.env.NODE_ENV === 'production') {
    return res.status(404).end()
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' })
  }

  const { topic, additionalInstruction } = req.body as {
    topic?: string
    additionalInstruction?: string
  }
  if (!topic || typeof topic !== 'string' || !topic.trim()) {
    return res.status(400).json({ error: 'topic is required' })
  }

  const today = new Date().toLocaleDateString('sv-SE')
  const prompt = buildAuthoringPrompt({
    today,
    topic: topic.trim(),
    additionalInstruction: typeof additionalInstruction === 'string' ? additionalInstruction.trim() : undefined,
  })
  const schemaPath = getSchemaFilePath()

  let rawOutput: string
  try {
    rawOutput = await runCodex({ prompt, schemaPath, timeoutMs: 300_000 })
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err)
    return res.status(500).json({
      error: 'codex execution failed',
      detail: message,
    })
  }

  // Parse and validate the JSON output
  let post: GeneratedPost
  try {
    post = JSON.parse(rawOutput) as GeneratedPost
  } catch {
    return res.status(500).json({
      error: 'codex returned invalid JSON',
      detail: rawOutput.slice(0, 500),
    })
  }

  // Defense-in-depth validation
  const validationError = validateGeneratedPost(post)
  if (validationError) {
    return res.status(500).json({ error: validationError, detail: rawOutput.slice(0, 500) })
  }

  // Auto-generate thumbnail when codex chose `generate`. On success, downgrade
  // the thumbnail to `reuse` so the publish endpoint takes the no-op path.
  let thumbnailGenerationError: string | undefined
  let thumbnailAutoGenerated = false
  if (post.thumbnail.mode === 'generate') {
    if (!post.thumbnail.generatePrompt || !post.thumbnail.generatePrompt.trim()) {
      thumbnailGenerationError = 'codex가 generate 모드를 선택했지만 generatePrompt가 비어 있어 자동 생성을 건너뛰었습니다.'
    } else {
      try {
        const seriesThumbnails = collectSeriesThumbnails(post.metadata)
        const result = await generateThumbnail({
          postFileNameWithoutExt: post.metadata.fileName.replace(/\.md$/, ''),
          generatePrompt: post.thumbnail.generatePrompt,
          seriesThumbnailFileNames: seriesThumbnails,
        })
        post.thumbnail = { mode: 'reuse', reuseFileName: result.savedFileName }
        thumbnailAutoGenerated = true
      } catch (err) {
        thumbnailGenerationError = err instanceof Error ? err.message : String(err)
      }
    }
  }

  return res.status(200).json({
    post,
    ...(thumbnailGenerationError ? { thumbnailGenerationError } : {}),
    ...(thumbnailAutoGenerated ? { thumbnailAutoGenerated: true } : {}),
  })
}

function validateGeneratedPost(post: GeneratedPost): string | null {
  if (!post || typeof post !== 'object') return 'Response is not an object'

  const { metadata, markdown, thumbnail } = post

  if (!metadata) return 'Missing metadata'
  if (!markdown || typeof markdown !== 'string') return 'Missing or invalid markdown'
  if (!thumbnail) return 'Missing thumbnail'

  if (!(metadata.category in CATEGORIES)) {
    return `Invalid category key: "${metadata.category}"`
  }
  if (!metadata.fileName || !/^[a-z0-9-]+\.md$/.test(metadata.fileName)) {
    return `Invalid fileName: "${metadata.fileName}" (must be kebab-case ending in .md)`
  }
  if (!metadata.publishedAt || !/^\d{4}-\d{2}-\d{2}$/.test(metadata.publishedAt)) {
    return `Invalid publishedAt: "${metadata.publishedAt}" (must be YYYY-MM-DD)`
  }
  if (!Array.isArray(metadata.tags) || metadata.tags.length === 0) {
    return 'tags must be a non-empty array'
  }
  if (!thumbnail.mode || !['reuse', 'generate'].includes(thumbnail.mode)) {
    return 'thumbnail.mode must be "reuse" or "generate"'
  }
  if (thumbnail.mode === 'reuse' && !thumbnail.reuseFileName) {
    return 'thumbnail.mode is "reuse" but reuseFileName is missing'
  }

  return null
}
